apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shop.fullname" . }}-worker
  labels:
    {{- include "shop.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "shop.selectorLabels" (dict "root" . "component" "worker") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shop.selectorLabels" (dict "root" . "component" "worker") | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        seccompProfile:
          type: {{ .Values.securityContext.seccompProfile.type }}
      containers:
        - name: worker
          image: "{{ .Values.image.registry }}/{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              value: {{ .Values.database.url | quote }}
            - name: POLL_INTERVAL
              value: {{ .Values.worker.pollInterval | quote }}
            {{- if .Values.worker.healthFail }}
            - name: HEALTH_FAIL
              value: "true"
            {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            capabilities:
              {{- toYaml .Values.securityContext.capabilities | nindent 14 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
