apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop.fullname" . }}-worker
  labels:
    {{- include "shop.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: {{ .Values.worker.service.type }}
  selector:
    {{- include "shop.selectorLabels" (dict "root" . "component" "worker") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.worker.service.port }}
      targetPort: http
